##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.10.0-B28] date: [Wed Aug 26 17:55:39 CEST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = miniHexa


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/pca9685.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Core/Src/system_stm32f4xx.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Appli/App/main_app.c \
Appli/Target/logshell_ctrl.c \
ST67W6X/App/app_st67w6x.c \
ST67W6X/Target/spi_port.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Middlewares/ST/ST67W6X_Network_Driver/Core/w6x_ble.c \
Middlewares/ST/ST67W6X_Network_Driver/Core/w6x_http.c \
Middlewares/ST/ST67W6X_Network_Driver/Core/w6x_mqtt.c \
Middlewares/ST/ST67W6X_Network_Driver/Core/w6x_net.c \
Middlewares/ST/ST67W6X_Network_Driver/Core/w6x_netif.c \
Middlewares/ST/ST67W6X_Network_Driver/Core/w6x_sys.c \
Middlewares/ST/ST67W6X_Network_Driver/Core/w6x_wifi.c \
Middlewares/ST/ST67W6X_Network_Driver/Utils/Logging/logging.c \
Middlewares/ST/ST67W6X_Network_Driver/Driver/W61_at/modem_cmd_handler.c \
Middlewares/ST/ST67W6X_Network_Driver/Driver/W61_at/w61_at_ble.c \
Middlewares/ST/ST67W6X_Network_Driver/Driver/W61_at/w61_at_common.c \
Middlewares/ST/ST67W6X_Network_Driver/Driver/W61_at/w61_at_mqtt.c \
Middlewares/ST/ST67W6X_Network_Driver/Driver/W61_at/w61_at_net.c \
Middlewares/ST/ST67W6X_Network_Driver/Driver/W61_at/w61_at_sys.c \
Middlewares/ST/ST67W6X_Network_Driver/Driver/W61_at/w61_at_wifi.c \
Middlewares/ST/ST67W6X_Network_Driver/Driver/W61_bus/spi_iface.c \
Middlewares/ST/ST67W6X_Network_Driver/Driver/W61_bus/w61_io.c \
Middlewares/ST/ST67W6X_Network_Driver/Utils/Misc/common_parser.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/api/api_lib.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/api/api_msg.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/api/err.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/api/if_api.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/api/netbuf.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/api/netdb.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/api/netifapi.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/api/sockets.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/api/tcpip.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv4/acd.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv4/autoip.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv4/dhcp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv4/etharp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv4/icmp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv4/igmp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv4/ip4.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv4/ip4_addr.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv4/ip4_frag.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv6/dhcp6.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv6/ethip6.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv6/icmp6.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv6/inet6.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv6/ip6.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv6/ip6_addr.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv6/ip6_frag.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv6/mld6.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ipv6/nd6.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/altcp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/altcp_tcp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/def.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/dns.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/inet_chksum.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/init.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/ip.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/mem.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/memp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/netif.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/pbuf.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/raw.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/stats.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/sys.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/tcp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/tcp_in.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/tcp_out.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/timeouts.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/core/udp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/bridgeif.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/bridgeif_fdb.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ethernet.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/auth.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/ccp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/chap-md5.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/chap-new.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/chap_ms.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/demand.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/eap.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/ecp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/eui64.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/fsm.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/ipcp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/ipv6cp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/lcp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/magic.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/mppe.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/multilink.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/ppp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/pppapi.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/pppcrypt.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/pppoe.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/pppol2tp.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/pppos.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/upap.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/utils.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/ppp/vj.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/src/netif/slipif.c \
Middlewares/Third_Party/SICS_Network_LwIP/LwIP/system/OS/sys_arch.c \
Appli/App/echo.c \
Core/Src/freertos.c \
Core/Src/stm32f4xx_hal_timebase_tim.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f411xe.s

# ASMM sources
ASMM_SOURCES = 

# ASMMC sources
ASMMC_SOURCE = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 
-DconfigTASK_NOTIFICATION_ARRAY_ENTRIES=8

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F401xE \
-DconfigTASK_NOTIFICATION_ARRAY_ENTRIES=8 \
-DST67_ARCH=W6X_ARCH_T01


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IST67W6X/App \
-IAppli/App \
-IAppli/Target \
-IST67W6X/Target \
-IMiddlewares/ST/ST67W6X_Network_Driver/Api \
-IMiddlewares/ST/ST67W6X_Network_Driver/Core \
-IMiddlewares/ST/ST67W6X_Network_Driver/Driver/W61_at \
-IMiddlewares/ST/ST67W6X_Network_Driver/Driver/W61_bus \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F401xx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMMC_SOURCES:.c=.o)))
vpath %.S $(sort $(dir $(ASMMC_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
